### ISSUE TITLE
Generating long videos

### ISSUE THREAD

**Issue by toyxyz** [Isi-dev/ComfyUI-UniAnimate-W#10]
Thanks for the great work as always! 

For the original Unianinmate, I used `python inference.py --cfg configs/UniAnimate_infer_long.yaml` to generate long videos, 

how can I use that feature in the ComfyUI version? 

![image](https://github.com/user-attachments/assets/04623a77-5418-4605-a174-0f12c9079db6)

**Comment by Isi-dev** [comment]
I haven't implemented the long video feature. I plan to do so in the nearest future.

**Comment by Isi-dev** [comment]
I have added support for long video generation with a new node: **Animate image with UniAnimate_Long**
