### ISSUE TITLE
Any chance you'll add an alternative to xformers?

### ISSUE THREAD

**Issue by defertoexpertise** [Isi-dev/ComfyUI-UniAnimate-W#12]
Running on macbook, but can't because your using xformers implicitly any chance you'd be able to add an alternative for those without xformers support.

**Comment by Isi-dev** [comment]
Xformers was used in the main unianimate project for optimization. All I did was modify the code to make it work with ComfyUI on Windows because that's the only OS I have access to. I'm not familiar with libraries that optimize attention mechanisms.
