### ISSUE TITLE
Runtime Error : use_libuv was requested but PyTorch was build without libuv support

### ISSUE THREAD

**Issue by myprivacygithub** [Isi-dev/ComfyUI-UniAnimate-W#13]
Runtime Error : use_libuv was requested but PyTorch was build without libuv support

**Comment by Isi-dev** [comment]
Try uninstalling torch torchvision torchaudio
Then reinstall based on your cuda version as follows:
# CUDA 11.8
conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia
# CUDA 12.1
conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=12.1 -c pytorch -c nvidia

Or:
# CUDA 11.8
pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
# CUDA 12.1
pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121

**Comment by SnikeGear** [comment]
in file:
.\ComfyUI-UniAnimate-W\tools\inferences\inference_unianimate_entrance.py
add in line 206:
os.environ["USE_LIBUV"] = "0"

works for me.

**Comment by Isi-dev** [comment]
> in file: .\ComfyUI\custom_nodes\ComfyUI-UniAnimate-W\tools\inferences\inference_unianimate_entrance.py add in line 206: os.environ["USE_LIBUV"] = "0"
> 
> and same in: .\ComfyUI\custom_nodes\ComfyUI-UniAnimate-W\tools\inferences\inference_unianimate_long_entrance.py add in line 212: os.environ["USE_LIBUV"] = "0"
> 
> works for me.

Thank you for the suggestion. Since this seems to be a common issue, I plan to study the role(s) played by libuv in the code and maybe include a check for its support, and disable accordingly, if I learn that there'll be no significant impact on performance.

**Comment by myprivacygithub** [comment]
Thank you @SnikeGear let me check.

**Comment by myprivacygithub** [comment]
not working for me, same error even after adding that line in both files.

**Comment by SnikeGear** [comment]
> not working for me, showing "cannot convert float NaN to integer" after adding that line in both files.

I think only works in PyTorch 2.4 and up

**Comment by Isi-dev** [comment]
> not working for me, showing "cannot convert float NaN to integer" after adding that line in both files.

I recently got the "cannot convert float NaN to integer" error and the cause seems to be that the dwpose model could not read some frames in the input video. I skipped a few frames in the video and didn't see the error again. You can try doing the same or use different inputs. I think SnikeGear's suggestion actually solved your 'use_libuv' issue.

**Comment by Isi-dev** [comment]
> in file: .\ComfyUI\custom_nodes\ComfyUI-UniAnimate-W\tools\inferences\inference_unianimate_entrance.py add in line 206: os.environ["USE_LIBUV"] = "0"
> 
> and same in: .\ComfyUI\custom_nodes\ComfyUI-UniAnimate-W\tools\inferences\inference_unianimate_long_entrance.py add in line 212: os.environ["USE_LIBUV"] = "0"
> 
> works for me.

I have updated the code as suggested. Thank you.

**Comment by myprivacygithub** [comment]
> > not working for me, showing "cannot convert float NaN to integer" after adding that line in both files.
> 
> I recently got the "cannot convert float NaN to integer" error and the cause seems to be that the dwpose model could not read some frames in the input video. I skipped a few frames in the video and didn't see the error again. You can try doing the same or use different inputs. I think SnikeGear's suggestion actually solved your 'use_libuv' issue.

Yes, tried some random videos and its working now. Thanks.

**Comment by Isi-dev** [comment]
> > > not working for me, showing "cannot convert float NaN to integer" after adding that line in both files.
> > 
> > 
> > I recently got the "cannot convert float NaN to integer" error and the cause seems to be that the dwpose model could not read some frames in the input video. I skipped a few frames in the video and didn't see the error again. You can try doing the same or use different inputs. I think SnikeGear's suggestion actually solved your 'use_libuv' issue.
> 
> Yes, tried some random videos and its working now. Thanks.

You're welcome.
