### ISSUE TITLE
Help me, help me~_~! When uploading animal pictures to generate videos, the faces of animals will turn into human faces. What should I do?

### ISSUE THREAD

**Issue by binnysz** [Isi-dev/ComfyUI-UniAnimate-W#16]
When uploading animal pictures to generate videos, the faces of animals will turn into human faces. What should I do?

**Comment by Isi-dev** [comment]
The UniAnimate model is for human image animation. I don't know if anyone has optimized the model to animate animals. Here's the link to the main project: https://github.com/ali-vilab/UniAnimate
