### ISSUE TITLE
Where is the seed?

### ISSUE THREAD

**Issue by caslix** [Isi-dev/ComfyUI-UniAnimate-W#2]
Hello! Thanks again for your implementation! Tell me, where can I specify the seed? Can I make a separate field? Thanks!

**Comment by Isi-dev** [comment]
You can change the seed on line 7 in \configs\UniAnimate_infer.py. Or you can make a separate field for the seed; I think it can be set on line 205 in \tools\inferences\inference_unianimate_entrance.py.

**Comment by Isi-dev** [comment]
Hello! I have modified the code to include a field for the seed.

**Comment by caslix** [comment]
Hello! Sorry for the long answer, there was no access to the computer. Thank you so much for your efforts, I will test it in the next few days.
