### ISSUE TITLE
main.py: error: unrecognized arguments: --output-directory

### ISSUE THREAD

**Issue by toyxyz** [Isi-dev/ComfyUI-UniAnimate-W#8]
Thanks for the great work! Unianimate node throws an error if --output-directory is set in ComfyUI. If it is not set, it works fine. 

```
usage: main.py [-h] [--cfg CFG_FILE] [--init_method INIT_METHOD] [--debug] [--windows-standalone-build] ...
main.py: error: unrecognized arguments: --output-directory
```

https://github.com/user-attachments/assets/f7ea6e9e-ea59-4dc8-9a87-48a4d72c3359

**Comment by Isi-dev** [comment]
I may not clearly understand this issue, but from my experience, the only output directory ComfyUI recognizes is the 'ComfyUI/Outputs' folder. If you use a Video Combine (VC) node to save your output and you input e.g. 'UniAnimate/vidName' in the  filename_prefix field of the VC node, then your output vid will be saved as vidName.mp4 in 'ComfyUI/Outputs/UniAnimate' folder. The error might be the way you specified the output folder (--output-directory). 
If what I have written is unrelated to the issue, please can you explain where and how you set the output directory?

**Comment by toyxyz** [comment]
In my case, I put a different output folder in the ComfyUI .bat. 

```
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --output-directory F:\Download\SDWEB_OUTPUT\Comfy
pause
```

**Comment by Isi-dev** [comment]
> In my case, I put a different output folder in the ComfyUI .bat. ComfyUi is on C, and the output folder is on F.
> 
> ```
> .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --output-directory F:\Download\SDWEB_OUTPUT\Comfy
> pause
> ```

Okay. It seems the Video Combine node has issues with your output folder settings. Please note that the output nodes (Video Combine or any other node you replace it with) is not part of the UniAnimate nodes. I used it in the workflow for display. The UniAnimate nodes in the workflow are 'Align & Generate poses for UniAnimate' and 'Animate image with UniAnimate', and the error message  has nothing to do with these nodes.

**Comment by toyxyz** [comment]
> > In my case, I put a different output folder in the ComfyUI .bat. ComfyUi is on C, and the output folder is on F.
> > ```
> > .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --output-directory F:\Download\SDWEB_OUTPUT\Comfy
> > pause
> > ```
> 
> Okay. It seems the Video Combine node has issues with your output folder settings. Please note that the output nodes (Video Combine or any other node you replace it with) is not part of the UniAnimate nodes. I used it in the workflow for display. The UniAnimate nodes in the workflow are 'Align & Generate poses for UniAnimate' and 'Animate image with UniAnimate', and the error message has nothing to do with these nodes.

The Video Combine node works fine when I change the output folder.  I've been using this node for a long time, and as long as I don't use it with Unianimate, I don't have any issues. 

The same error occurs when using only the preview image node. 

![image](https://github.com/user-attachments/assets/33d31842-ba6d-4cfa-a1f7-8426f8c1ec60)


```
2024-08-16 19:02:41,972 - dw pose extraction - INFO - There are 1 frames for extracting poses
2024-08-16 19:02:41,973 - dw pose extraction - INFO - LOAD: DW Pose Model
This file is located at C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-UniAnimate-W\dwpose
2024-08-16 19:02:42,556 - dw pose extraction - INFO - Processing frame 1/1
2024-08-16 19:02:59,491 - dw pose extraction - INFO - All frames have been processed.
1
usage: main.py [-h] [--cfg CFG_FILE] [--init_method INIT_METHOD] [--debug] [--windows-standalone-build] ...
main.py: error: unrecognized arguments: --output-directory
```

**Comment by Isi-dev** [comment]
> > > In my case, I put a different output folder in the ComfyUI .bat. ComfyUi is on C, and the output folder is on F.
> > > ```
> > > .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --output-directory F:\Download\SDWEB_OUTPUT\Comfy
> > > pause
> > > ```
> > 
> > 
> > Okay. It seems the Video Combine node has issues with your output folder settings. Please note that the output nodes (Video Combine or any other node you replace it with) is not part of the UniAnimate nodes. I used it in the workflow for display. The UniAnimate nodes in the workflow are 'Align & Generate poses for UniAnimate' and 'Animate image with UniAnimate', and the error message has nothing to do with these nodes.
> 
> The Video Combine node works fine when I change the output folder. I've been using this node for a long time, and as long as I don't use it with Unianimate, I don't have any issues.
> 
> The same error occurs when using only the preview image node.
> 
> ![image](https://private-user-images.githubusercontent.com/8006000/358547106-33d31842-ba6d-4cfa-a1f7-8426f8c1ec60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDM4MzksIm5iZiI6MTcyMzgwMzUzOSwicGF0aCI6Ii84MDA2MDAwLzM1ODU0NzEwNi0zM2QzMTg0Mi1iYTZkLTRjZmEtYTFmNy04NDI2ZjhjMWVjNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTAxODU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzM5ZDY1Yjg0OTViODM1MTRkZGUzMjRlNTMxZjhjNGY3ZTE1ODA5MzQ0OGIzYzVlYzY3MTU3N2U3OTFkMjkyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9aaIzmCjCYIZasAzsPz7pv4mRMNNnQZPogjgbz4urtQ)
> 
> ```
> 2024-08-16 19:02:41,972 - dw pose extraction - INFO - There are 1 frames for extracting poses
> 2024-08-16 19:02:41,973 - dw pose extraction - INFO - LOAD: DW Pose Model
> This file is located at C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-UniAnimate-W\dwpose
> 2024-08-16 19:02:42,556 - dw pose extraction - INFO - Processing frame 1/1
> 2024-08-16 19:02:59,491 - dw pose extraction - INFO - All frames have been processed.
> 1
> usage: main.py [-h] [--cfg CFG_FILE] [--init_method INIT_METHOD] [--debug] [--windows-standalone-build] ...
> main.py: error: unrecognized arguments: --output-directory
> ```

Okay, sorry for my misunderstanding. I will try to reproduce the error at my end by following your settings and see if I can figure out the cause. I am currently away from my system. Hopefully I will get back to you within 4 days.

**Comment by Isi-dev** [comment]
I just updated the code to handle the --output-directory error. You can either replace your utils/config.py with the one in the repository or download the code again and try it. Please notify me of the outcome.

**Comment by toyxyz** [comment]
> I just updated the code to handle the --output-directory error. You can either replace your utils/config.py with the one in the repository or download the code again and try it. Please notify me of the outcome.

It now work without issue. Thank you!

https://github.com/user-attachments/assets/905ec394-3abe-4efc-af68-77842f8386e2
