### ISSUE TITLE
Models directory

### ISSUE THREAD

**Issue by NicholasKao1029** [Isi-dev/ComfyUI-UniAnimate-W#9]
Is it possible to have the models be in the `/comfyui/models/...` directory path? I find it better this way because it allows for others custom_nodes to share the models also makes model management much easier.

**Comment by Isi-dev** [comment]
> Is it possible to have the models be in the `/comfyui/models/...` directory path? I find it better this way because it allows for others custom_nodes to share the models also makes model management much easier.

Thanks for the suggestion. It's possible, but all the installation guides I have made on these nodes (writings and videos) are based on the current directory path of the models). I will follow your suggestion in subsequent projects. If you are interested, I can make a written guide on how to go about it about 4 days from today.

**Comment by NicholasKao1029** [comment]
That's great to hear, I appreciate you writing this node!

**Comment by Isi-dev** [comment]
To have the models in the /comfyui/models/... directory path, do the following:

Move the 5 models from '\ComfyUI-UniAnimate-W-main\checkpoints' to '\ComfyUI\models\checkpoints'

We will modify the following files:
'\ComfyUI-UniAnimate-W-main\dwpose\wholebody.py'
'\ComfyUI-UniAnimate-W-main\tools\inferences\inference_unianimate_entrance.py'
'\ComfyUI-UniAnimate-W-main\tools\modules\autoencoder.py'
'\ComfyUI-UniAnimate-W-main\tools\modules\clip_embedder.py'

Add to the beginning of each file: import folder_paths

In '\ComfyUI-UniAnimate-W-main\dwpose\wholebody.py',
Change lines 20 & 21, 
onnx_det = os.path.join(parent_directory, 'checkpoints/yolox_l.onnx')
onnx_pose = os.path.join(parent_directory, 'checkpoints/dw-ll_ucoco_384.onnx')
to:
onnx_det = os.path.join(folder_paths.models_dir, 'checkpoints/yolox_l.onnx')
onnx_pose = os.path.join(folder_paths.models_dir, 'checkpoints/dw-ll_ucoco_384.onnx')


In '\ComfyUI-UniAnimate-W-main\tools\inferences\inference_unianimate_entrance.py',
Change line 284,
unifiedModel = os.path.join(root_directory, 'checkpoints/unianimate_16f_32f_non_ema_223000.pth')
to:
unifiedModel = os.path.join(folder_paths.models_dir, 'checkpoints/unianimate_16f_32f_non_ema_223000.pth')


In '\ComfyUI-UniAnimate-W-main\tools\modules\autoencoder.py',
Change line 69,
pretrained = os.path.join(root_directory, 'checkpoints/v2-1_512-ema-pruned.ckpt')
to:
pretrained = os.path.join(folder_paths.models_dir, 'checkpoints/v2-1_512-ema-pruned.ckpt')


In '\ComfyUI-UniAnimate-W-main\tools\modules\clip_embedder.py',
Change lines 33,107, & 186, (You only need to change line 186, but you can also change others.)
pretrained = os.path.join(root_directory, 'checkpoints/open_clip_pytorch_model.bin')
to:
pretrained = os.path.join(folder_paths.models_dir, 'checkpoints/open_clip_pytorch_model.bin')
